# Generated by Django 2.2.6 on 2019-12-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beacon_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='isActive',
        ),
        migrations.AddField(
            model_name='beacon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
