# Generated by Django 2.2.6 on 2019-12-10 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191209_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place_type', models.CharField(blank=True, choices=[('ROOM', 'Room'), ('COFFEE', 'Coffee'), ('STAIRS', 'Stairs'), ('', 'Undefined')], default='', max_length=10, verbose_name='type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Place'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
