# Generated by Django 2.2.6 on 2019-12-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191210_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('ROOM', 'Room'), ('COFFEE', 'Coffee'), ('STAIRS', 'Stairs'), ('JOINT', 'Joint'), ('', 'Undefined')], default='', max_length=10, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertex1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex1', to='core.Place')),
                ('vertex2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex2', to='core.Place')),
            ],
        ),
    ]
